name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    name: Run on Chrome 88
    runs-on: ubuntu-20.04
    container: cypress/browsers:node14.17.0-chrome88-ff89
    steps:
      - uses: actions/checkout@v2

      - name: Run Dev Server
        run: npm start

      - name: Run Cypress tests
        run: npm run test:chrome
        continue-on-error: true
